export const SurpriseMePrompts = [
  'A floating island in the sky with waterfalls cascading down its edges, digital art',
  'A mystical forest inhabited by glowing fireflies and mythical creatures, digital painting',
  'A futuristic cityscape with holographic billboards and flying drones, cyberpunk art',
  'A steampunk-inspired airship soaring through the clouds, digital illustration',
  'A giant robotic octopus emerging from the depths of the ocean, digital art',
  'An ancient temple hidden within a dense jungle, 3D render',
  'A celestial being made of stardust and constellations, digital art',
  'A time-traveling adventurer exploring ancient ruins, sci-fi illustration',
  'A magical library with floating books and animated creatures, digital painting',
  'A desert landscape with sand dunes and a caravan of camels, digital art',
  'A fantastical underwater city with mermaids and bioluminescent sea life, digital illustration',
  'A cybernetic forest with neon-colored trees and bioengineered animals, concept art',
  'A dragon and phoenix engaged in an aerial battle amidst the clouds, fantasy art',
  'A futuristic metropolis with flying cars and skyscrapers touching the sky, 3D rendering',
  'An enchanted garden with talking animals and enchanted flowers, digital painting',
  'A post-apocalyptic wasteland inhabited by cyborgs and mutated creatures, digital illustration',
  'A magical marketplace filled with exotic creatures and enchanted items, fantasy concept art',
  'A group of intergalactic explorers encountering a cosmic storm, sci-fi digital art',
  'A hidden cave filled with ancient crystals and glowing runes, digital painting',
  'An interstellar train traveling through space, transporting alien passengers, digital art',
  'A giant waterfall with a hidden cave behind it, home to a secretive civilization, 3D render',
  'A mysterious portal that leads to different dimensions, digital illustration',
  'A futuristic racing track with anti-gravity vehicles, racing towards a neon finish line, concept art',
  'A floating city above the clouds, inhabited by advanced AI beings, digital art',
  'An ancient tree with magical properties, guarded by mythical creatures, fantasy illustration',
  'A cosmic dance of planets and stars in a distant galaxy, digital painting',
  'A high-tech underwater research facility exploring the depths of the ocean, sci-fi concept art',
  'A lush alien rainforest with bioluminescent flora and fauna, digital art',
  'A city engulfed in a perpetual thunderstorm, illuminated by flashes of lightning, digital illustration',
  'A brave astronaut exploring the surface of a distant moon, digital painting',
  'A tribe of elemental beings controlling the forces of nature, fantasy concept art',
  'A colossal sea serpent emerging from the depths of the ocean, digital art',
  'An otherworldly music festival attended by extraterrestrial beings, sci-fi concept art',
  'A futuristic cybernetic warrior with glowing armor and powerful weapons, digital illustration',
  'A hidden cave with ancient hieroglyphs depicting the history of an alien civilization, digital art',
  'An abandoned space station floating in the vastness of space, sci-fi digital painting',
  'A group of adventurers sailing on the back of a giant turtle through a magical sea, fantasy art',
  'A cyberpunk city at night, with holographic billboards and neon-lit alleyways, digital illustration',
  'A majestic ice castle ruled by a powerful ice queen, fantasy concept art',
  'A fleet of alien spaceships descending upon Earth, digital art',
  'A tribe of nomadic warriors riding mechanical beasts through a desert wasteland, concept art',
  'A magical portal hidden within an ancient stone archway, fantasy digital art',
  'A group of explorers navigating through a treacherous asteroid field, sci-fi illustration',
  'A steampunk-inspired laboratory with intricate machinery and gears, digital art',
  'An ancient cosmic library containing knowledge from across the universe, digital painting',
  'A colony on a distant planet where flora and fauna have evolved in unexpected ways, sci-fi concept art',
  'A haunted mansion with eerie glowing spirits, fantasy art',
  'A futuristic cyberpunk street scene with flying cars and holographic advertisements, digital illustration',
  'A mythical creature soaring through the skies, leaving a trail of stardust, digital art',
  'An underwater civilization of merfolk and underwater cities, fantasy concept art',
  'A space fleet engaging in an epic battle among the stars, sci-fi digital painting',
  'A hidden underground city with bioluminescent plants, home to a reclusive civilization, digital art',
  'A time-traveling train station connecting different historical eras, digital illustration',
  'A futuristic amusement park with advanced VR rides and attractions, concept art',
  'An enchanted forest with talking animals and sentient trees, fantasy digital art',
  'A group of interstellar travelers encountering a cosmic phenomenon, sci-fi illustration',
  'A floating fortress defended by powerful elemental guardians, digital painting',
  'A futuristic cityscape with flying cars and massive holographic billboards, digital art',
  'An ancient temple guarded by mythical creatures, fantasy concept art',
  'A space colony on a distant planet, bustling with alien life, sci-fi concept art',
  'A hidden cave with glowing crystals and ancient alien artifacts, digital art',
  'An advanced civilization living in harmony with nature on a distant planet, digital illustration',
  'A post-apocalyptic cityscape reclaimed by nature, sci-fi digital painting',
  'A group of adventurers exploring an underground labyrinth filled with traps and treasures, fantasy art',
  'A cyberpunk hacker navigating through a virtual reality world, concept art',
  'An underwater metropolis with transparent domes and advanced technology, digital art',
  'A mystical portal revealing a glimpse of parallel dimensions, fantasy concept art',
  'A fleet of starships embarking on an intergalactic voyage, sci-fi illustration',
  'A futuristic space station orbiting a distant planet, digital painting',
  'An enchanted garden with talking animals and magical plants, fantasy digital art',
  'A group of explorers investigating an ancient alien artifact, sci-fi concept art',
  'A steampunk airship racing through the clouds, digital art',
  'An ancient forest with towering trees and glowing mushrooms, fantasy concept art',
  'A space traveler witnessing the birth of a new star, sci-fi illustration',
  'A futuristic city with flying cars and massive holographic displays, digital painting',
  'An underwater civilization with advanced technology and marine creatures, digital art',
  'A group of adventurers crossing a treacherous bridge over a chasm, fantasy art',
  'A cyberpunk cityscape at sunset, with neon lights and futuristic skyscrapers, concept art',
  'An alien marketplace with vendors selling exotic goods, sci-fi digital art',
  'A mythical creature frolicking in a field of colorful flowers, fantasy concept art',
  'A futuristic space colony with biodomes and advanced architecture, digital illustration',
  'An ancient ruin with mysterious carvings and hidden passages, fantasy digital painting',
  'A group of space explorers encountering a beautiful cosmic nebula, sci-fi concept art',
  'A cybernetic warrior with glowing tattoos and augmented limbs, digital art',
  'An underwater cave filled with glowing crystals and mysterious sea life, digital illustration',
  'A futuristic cityscape with flying cars and towering megastructures, concept art',
  'A hidden library of magical books and ancient scrolls, fantasy art',
  'A space traveler gazing at a distant galaxy from the edge of a black hole, sci-fi illustration',
  'A cyberpunk street market bustling with people and futuristic technology, digital painting',
  'An ancient temple hidden in a lush jungle, guarded by mythical creatures, fantasy digital art',
  'A space fleet engaged in an intergalactic space battle, sci-fi concept art',
  'A group of explorers traversing a treacherous ice cave, digital art',
  'An underwater city with bioluminescent creatures and advanced architecture, digital illustration',
  'A post-apocalyptic wasteland with remnants of advanced technology, concept art',
  'A mystical portal opening to a realm of magic and wonder, fantasy concept art',
  'A futuristic cityscape at night, illuminated by neon lights and holographic displays, digital art',
  'An ancient forest inhabited by ethereal spirits and magical creatures, fantasy digital painting',
  'A group of space travelers discovering an abandoned alien spaceship, sci-fi illustration',
  'A cyberpunk cityscape with rain-soaked streets and towering skyscrapers, concept art',
  'An alien world with floating islands and exotic flora, digital art',
  ];